[package]
name = "adv_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
env_logger = "0.10.0"
log = "0.4.17"
oracle = "0.5.7"
rand = "0.8.5"
sha2 = "0.10.6"
